name: Unity Activation

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request Activation File
    runs-on: ubuntu-latest

    steps:
      - name: Request Manual Activation File
        uses: game-ci/unity-request-activation-file@v2
        id: getalf

      - name: Upload .alf Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v${{ steps.getalf.outputs.unityVersion }}.alf
          path: ${{ steps.getalf.outputs.filePath }}

      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload .ulf Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v${{ steps.getalf.outputs.unityVersion }}_Professional.ulf
          path: Unity_v${{ steps.getalf.outputs.unityVersion }}_Professional.ulf
